README.md, src/components/abciapp/Cargo.toml, src/components/bugchecker/Cargo.toml, src/components/contracts/baseapp/Cargo.toml, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/mocks/Cargo.toml, src/components/contracts/primitives/storage/Cargo.toml, src/components/contracts/primitives/types/Cargo.toml, src/components/finutils/Cargo.toml, src/components/wasm/Cargo.toml, src/ledger/Cargo.toml, src/libs/credentials/Cargo.toml, src/libs/globutils/Cargo.toml
=> add badge on platform

src/components/abciapp/Cargo.toml, src/components/abciapp/src/abci/server/callback/mod.rs, src/components/abciapp/src/api/submission_server/mod.rs, src/components/contracts/modules/account/src/impls.rs, src/components/contracts/modules/ethereum/tests/ethereum_integration.rs, src/components/contracts/modules/evm/tests/evm_integration.rs, src/components/contracts/modules/template/Cargo.toml, src/components/contracts/modules/template/tests/template_integration.rs, src/components/contracts/primitives/types/src/assemble.rs, src/components/contracts/primitives/utils/src/lib.rs, src/components/contracts/primitives/utils/src/tx.rs, src/components/contracts/rpc/src/eth.rs, src/components/finutils/Cargo.toml, src/components/finutils/src/common/evm.rs
* update contracts module unit test.
=> fix deliver_tx tx twice deserialize

src/components/contracts/rpc/README.md, src/components/contracts/rpc/src/lib.rs
=> unfold asterisk wildcard declaration & add rpc module README.md

src/components/abciapp/src/abci/mod.rs, src/components/abciapp/src/api/query_server/query_api/ledger_api.rs, src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/abciapp/src/api/query_server/query_api/server.rs, src/components/abciapp/src/api/query_server/query_api/service.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/staking/mod.rs, src/ledger/src/store/api_cache.rs, src/ledger/src/store/helpers.rs, src/ledger/src/store/mod.rs, src/ledger/src/store/test.rs
- move the cache data of `QueryServer` into ledger
- update the cache data along with each block one by one
- share the same low-level DB-backend with on-chain logics
- copy ledger in lightweight mode, instead of re-calculation
- performance: use `try lock` style, allow data latency
- stability: avoid possible errors in re-calculation
no errors occur when syncing with mainnet 
=> optimize API layer: performance & stability

src/components/contracts/baseapp/Cargo.toml, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/storage/Cargo.toml
=> use taged deps

src/components/abciapp/src/api/query_server/query_api/ledger_api.rs, src/ledger/src/staking/mod.rs
fix incorrect bond_amount in DelegationInfo
* **Reletad issue**
close FindoraNetwork/platform-readonly#549
=> fix incorrect unbond_amount

src/components/abciapp/Cargo.toml, src/components/abciapp/src/abci/server/callback/mod.rs, src/components/contracts/baseapp/Cargo.toml, src/components/contracts/baseapp/src/app.rs, src/components/contracts/baseapp/src/lib.rs, src/components/contracts/baseapp/src/modules.rs, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/modules/account/src/impls.rs, src/components/contracts/modules/account/src/tests.rs, src/components/contracts/modules/ethereum/Cargo.toml, src/components/contracts/modules/ethereum/src/impls.rs, src/components/contracts/modules/ethereum/src/lib.rs, src/components/contracts/modules/evm/src/impls.rs, src/components/contracts/modules/evm/src/lib.rs, src/components/contracts/modules/evm/src/runtime/stack.rs, src/components/contracts/modules/evm/tests/evm_integration.rs, src/components/contracts/modules/template/src/lib.rs, src/components/contracts/modules/template/tests/template_integration.rs, src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/core/src/context.rs, src/components/contracts/primitives/core/src/transaction.rs, src/components/contracts/primitives/mocks/src/lib.rs, src/components/contracts/primitives/storage/Cargo.toml, src/components/contracts/primitives/storage/src/lib.rs, src/components/contracts/primitives/storage/src/tests.rs, src/components/contracts/primitives/storage/src/types/double_map.rs, src/components/contracts/primitives/storage/src/types/map.rs, src/components/contracts/primitives/storage/src/types/value.rs
=> Optimize stateless storage

src/components/abciapp/src/abci/server/callback/mod.rs, src/components/contracts/primitives/core/src/context.rs, src/components/contracts/primitives/storage/src/tests.rs, src/components/finutils/src/common/utils.rs, src/components/finutils/src/txn_builder/mod.rs, src/ledger/Cargo.toml, src/ledger/src/data_model/effects.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/store/mod.rs, src/ledger/src/store/test.rs
=> Feat triple masking v2 ledger status

src/components/abciapp/src/abci/server/callback/mod.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/store/mod.rs
=> optimize performance

src/components/abciapp/Cargo.toml, src/components/abciapp/src/abci/server/callback/mod.rs, src/components/bugchecker/Cargo.toml, src/components/contracts/baseapp/Cargo.toml, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/modules/ethereum/Cargo.toml, src/components/contracts/modules/evm/Cargo.toml, src/components/contracts/modules/template/Cargo.toml, src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/evm/Cargo.toml, src/components/contracts/primitives/mocks/Cargo.toml, src/components/contracts/primitives/storage/Cargo.toml, src/components/contracts/primitives/traits/Cargo.toml, src/components/contracts/primitives/types/Cargo.toml, src/components/contracts/primitives/utils/Cargo.toml, src/components/contracts/primitives/wasm/Cargo.toml, src/components/contracts/rpc/Cargo.toml, src/components/finutils/Cargo.toml, src/components/wasm/Cargo.toml, src/ledger/Cargo.toml, src/ledger/src/data_model/mod.rs, src/ledger/src/store/api_cache.rs, src/ledger/src/store/mod.rs, src/libs/bitmap/Cargo.toml, src/libs/credentials/Cargo.toml, src/libs/cryptohash/Cargo.toml, src/libs/globutils/Cargo.toml, src/libs/merkle_tree/Cargo.toml, src/libs/sliding_set/Cargo.toml
=> optimize deps & performance

docs/recover.md, src/components/abciapp/src/abci/config.rs, src/components/abciapp/src/abci/server/callback/mod.rs, src/components/abciapp/src/abci/snap.rs, src/components/abciapp/src/bins/findorad.rs
=> enhance rollback mechanism

src/components/abciapp/src/api/query_server/query_api/ledger_api.rs, src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/finutils/src/bins/fn.rs, src/components/finutils/src/bins/fn.yml, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs, src/components/finutils/src/txn_builder/mod.rs, src/components/wasm/src/wasm.rs, src/ledger/Cargo.toml, src/ledger/src/store/mod.rs, src/ledger/src/store/test.rs, src/libs/globutils/Cargo.toml, src/libs/globutils/src/wallet.rs
=> Ftm ledger state query

src/components/finutils/src/bins/stt.rs, tools/devnet/startnodes.sh
Fixed stt binary to make local devmet working
=> Fixed stt for local devnet

src/components/abciapp/src/abci/mod.rs, src/components/contracts/rpc/Cargo.toml, src/components/contracts/rpc/src/eth.rs, src/components/contracts/rpc/src/eth_filter.rs, src/components/contracts/rpc/src/lib.rs
1. Implemented log filters and block filters
2. Filter pool thread to clean up expired filters.
=> Feat evm v2 log and block filters

docs/upgrade.md, src/components/abciapp/src/abci/staking/abci_mock_test.rs, src/components/abciapp/src/abci/staking/test.rs, src/components/bugchecker/src/bins/xx.rs, src/components/finutils/src/bins/stt/init/i_testing.rs, src/components/finutils/src/bins/stt/init/mod.rs, src/components/finutils/src/bins/stt/stt.rs, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs, src/components/finutils/src/txn_builder/mod.rs, src/components/wasm/src/wasm.rs
=> decrease staking amounts

README.md, docs/CHANGELOG.md, docs/contribution_guide.md
=> add CHANGELOG

Makefile, src/components/abciapp/src/api/query_server/query_api/ledger_api.rs, src/ledger/Cargo.toml
=> optimize some history-style APIs

src/ledger/Cargo.toml, src/ledger/src/staking/mod.rs
use `biguint` instead of `u128`
=> Fix delegation rewards overflow using bigint.

src/components/abciapp/Cargo.toml, src/components/abciapp/src/api/query_server/query_api/server.rs, src/components/bugchecker/Cargo.toml, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/primitives/mocks/Cargo.toml, src/components/contracts/primitives/types/Cargo.toml, src/components/finutils/src/bins/fn.rs, src/components/finutils/src/bins/fn.yml, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs, src/components/finutils/src/txn_builder/mod.rs, src/components/wasm/Cargo.toml, src/ledger/src/data_model/effects.rs, src/ledger/src/data_model/mod.rs, src/libs/credentials/Cargo.toml
=> Integrating Intrisic Fee for Bar to Abar conversion operation

src/components/abciapp/src/abci/server/callback/mod.rs, src/components/contracts/modules/evm/src/lib.rs, tools/devnet/startnodes.sh
=> fix internal transfer and replace todo!

src/ledger/src/store/mod.rs
Change APY modifier from 0.2 to 0.536
https://www.notion.so/findora/PoS-Stage-1-Consensus-Rewards-Penalties-Backend-72f5c9a697ff461c89c3728e34348834
=> Change APY modifier based on v7 rate.

src/components/contracts/modules/ethereum/src/lib.rs, src/components/finutils/src/bins/stt/init/mod.rs, src/components/finutils/src/bins/stt/stt.rs
Added skip_validator option back to stt to support local single-node devnet
Fixed #26
Added ChainId checking in ValidateUnsigned()
=> added skip_validator option to stt to suport single-node local devnet

src/components/contracts/rpc/src/eth.rs
=> fix platform issue 103

src/ledger/Cargo.toml
=> change dependency from bulletproofs to bp

src/components/abciapp/src/api/query_server/query_api/ledger_api.rs
fix bug to include data with a power of 0 when query validators
=> fix bug to include data with a power of 0 when query validators

src/components/abciapp/src/api/query_server/query_api/ledger_api.rs
=> fix lifetime rewards in query_validator_detail

src/components/abciapp/src/api/query_server/query_api/mod.rs
add api 
Calculation of relevant data
=> feat api get_total_supply

src/ledger/src/data_model/mod.rs, src/ledger/src/staking/mod.rs
=> fix wasm build error

src/components/contracts/baseapp/src/lib.rs, src/components/contracts/modules/ethereum/src/impls.rs, src/components/contracts/modules/ethereum/src/lib.rs, src/components/contracts/modules/evm/src/impls.rs, src/components/contracts/modules/evm/src/lib.rs, src/components/contracts/modules/evm/src/runtime/runner.rs, src/components/contracts/modules/evm/src/runtime/stack.rs, src/components/contracts/modules/evm/tests/evm_integration.rs, src/components/contracts/primitives/types/Cargo.toml, src/components/contracts/primitives/types/src/crypto.rs
This PR was meant to fix the issue: 
https://github.com/FindoraNetwork/platform/issues/111
* New type added to wrap the existing hash (H256)
* ToString trait is implemented for the new type(HA256) such that the entire hash is displayed in hex
* Modifications were made to the corresponding stores using the H256 type.
=> Added new type to wrap H256 - NOT TESTED YET

src/ledger/src/staking/mod.rs
=> Fix compatibility for better name and doc.

src/components/contracts/baseapp/src/lib.rs, src/components/contracts/modules/ethereum/Cargo.toml, src/components/contracts/modules/ethereum/src/impls.rs, src/components/contracts/modules/ethereum/src/lib.rs
1. Enforces gas limit range [21_000, u32::max_value()]
2. Extended versioning to 3 months
3. Set first EVM height to same height as APY upgrading, 139_8000
=> checks gas limit

src/components/contracts/modules/account/src/lib.rs, src/components/finutils/src/common/evm.rs, tools/devtool
1. add more error checking to `fn`
2. response error if serialization failed
=> more error checking for abci_query

docs/CHANGELOG.md
=> CHANGELOG update

src/components/wasm/src/wasm.rs, src/ledger/src/converter/mod.rs
1. Checks receiver address format when converting UTXO to account based FRA
=> check EVM receiver's address

src/components/contracts/modules/evm/src/impls.rs, src/components/contracts/rpc/src/eth.rs
fix frc20 precompile address when query frc20 account code
close #146 
=> fix frc20 code

docs/CHANGELOG.md
Update change log for IERC20 fix
=> Change Log

.github/workflows/Develop.yml, .github/workflows/Main.yml, .github/workflows/Master.yml, .github/workflows/Others.yml
=> fix the ecr login issue

.github/workflows/Release.yml
=> fix ecr login in release

src/ledger/src/store/api_cache.rs, src/ledger/src/store/mod.rs
=> check the lost owner memos.

src/ledger/src/store/api_cache.rs
=> fix none api cache error.

src/components/abciapp/src/abci/config.rs, src/components/abciapp/src/abci/server/callback/mod.rs, src/ledger/src/store/api_cache.rs, tools/devnet/startnodes.sh
=> disable evm

src/components/abciapp/src/abci/server/callback/mod.rs, src/ledger/src/store/mod.rs
fix node crash and reset update height
=> fix node crash and reset update height

src/components/abciapp/src/abci/server/callback/mod.rs, src/ledger/src/store/api_cache.rs
=> fix error compute apphash of abci info

src/components/contracts/baseapp/src/app.rs, src/components/contracts/modules/ethereum/src/impls.rs, src/components/contracts/modules/evm/src/runtime/runner.rs, src/components/contracts/primitives/core/src/transaction.rs, src/components/contracts/rpc/src/eth.rs, tools/devnet/startnodes.sh
replay evm error to tendermint check/deliver tx response
=> fix reentrant call error

docs/CHANGELOG.md, src/components/abciapp/src/abci/mod.rs, src/components/abciapp/src/abci/staking/mod.rs, src/components/contracts/baseapp/Cargo.toml, src/components/contracts/baseapp/src/app.rs, src/components/contracts/baseapp/src/extensions.rs, src/components/contracts/baseapp/src/lib.rs, src/components/contracts/baseapp/src/modules.rs, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/modules/account/src/impls.rs, src/components/contracts/modules/account/src/tests.rs, src/components/contracts/modules/ethereum/Cargo.toml, src/components/contracts/modules/ethereum/src/impls.rs, src/components/contracts/modules/ethereum/tests/ethereum_db.rs, src/components/contracts/modules/ethereum/tests/ethereum_integration.rs, src/components/contracts/modules/evm/src/impls.rs, src/components/contracts/modules/evm/src/runtime/stack.rs, src/components/contracts/modules/evm/tests/evm_integration.rs, src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/core/src/context.rs, src/components/contracts/primitives/core/src/transaction.rs, src/components/contracts/primitives/mocks/src/lib.rs, src/components/contracts/primitives/storage/Cargo.toml, src/components/contracts/primitives/traits/src/base.rs, src/components/contracts/rpc/Cargo.toml, src/components/contracts/rpc/src/eth.rs, src/components/contracts/rpc/src/lib.rs, tools/devnet/env.sh
1.  remove extra commit/discard from findora backend for evm
2.  discard chain state if evm call error happens
3.  use `broadcast_tx_sync` in `send_raw_transaction`
4. avoid using old chain state used in web3.0 APIs
5. RialtoBridge nonce fix.
=> fix reentrant revert error

src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/core/src/lib.rs, src/components/finutils/Cargo.toml, src/components/finutils/src/common/evm.rs
Remove some unused type and deps for finutils.
=> add musl compile support

src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/core/src/lib.rs, src/components/wasm/src/wasm.rs
1. fixing the main branch cannot build wasm32 architecture
2. let the make lint command can pass without error out on warnings
nope
=> fixing main branch cannot build wasm32 architecture

.gitignore, src/components/contracts/primitives/wasm/src/wasm.rs, src/components/contracts/rpc/src/eth.rs, src/components/wasm/src/wasm.rs, src/components/wasm/src/wasm_data_model.rs
1. handle blocknumber
2. binary searching estimate gas
=> fix estimate_gas api

.github/workflows/WasmCatDelete.yml
=> adding Wasmcat delete action

src/components/config/src/abci/mod.rs, src/components/contracts/modules/evm/Cargo.toml, src/components/contracts/modules/evm/src/runtime/stack.rs
1) enable evm substate
2) change log
=> enable evm substate

docs/CHANGELOG.md, src/components/contracts/rpc/Cargo.toml, src/components/finutils/Cargo.toml, src/ledger/Cargo.toml
1) Updated change log
2) Set 177_5600 as upgrading height. Around 9:40 AM, PST Feb. 17
=> Added change log and upgrading height 177_5600

docs/CHANGELOG.md, src/components/config/src/abci/mod.rs
1) Set upgrading height at 178_7600. Around 3pm PST, Feb 19
2) Update change log.
=> mainnet upgrading roughly at 9AM PST, Feb 22

src/components/abciapp/Cargo.toml, src/components/abciapp/src/abci/server/callback/mod.rs
=> reduce log to single line

src/components/abciapp/src/api/query_server/query_api/ledger_api.rs, src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/abciapp/src/api/submission_server/submission_api.rs, src/components/config/src/abci/mod.rs, src/components/contracts/baseapp/Cargo.toml, src/components/contracts/baseapp/src/app.rs, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/modules/evm/Cargo.toml, src/components/contracts/modules/xhub/Cargo.toml, src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/mocks/Cargo.toml, src/components/contracts/primitives/traits/Cargo.toml, src/components/contracts/primitives/types/Cargo.toml, src/components/contracts/primitives/utils/Cargo.toml, src/components/finutils/src/api/mod.rs, src/components/finutils/src/txn_builder/mod.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/staking/mod.rs, src/ledger/src/store/mod.rs, src/libs/bitmap/src/lib.rs, src/libs/merkle_tree/src/lib.rs
=> Fix clippy errors

src/libs/bitmap/Cargo.toml, src/libs/bitmap/src/lib.rs, src/libs/bitmap/src/test.rs
=> Fixing clippy error with initialized tuples

src/libs/bitmap/Cargo.toml, src/libs/bitmap/src/lib.rs, src/libs/bitmap/src/test.rs, src/libs/cryptohash/src/lib.rs
=> fix wasm compile error

src/components/wasm/src/wasm.rs, src/components/wasm/src/wasm_data_model.rs
Hot fix for missing wasm-bindgen tags which were accidentally deleted
=> Fix wasm bind tags

src/components/finutils/src/txn_builder/mod.rs, src/ledger/src/data_model/effects.rs, src/ledger/src/store/mod.rs
Waiting PR https://github.com/FindoraNetwork/zei/pull/29 merged.
=> Apply precompute verifier parameters

src/components/finutils/src/txn_builder/mod.rs, src/components/wasm/Cargo.toml, src/components/wasm/src/wasm.rs
This implement the function described in the jira task with the same name of the branch
=> This includes the function descibed in FO-887

.github/workflows/Develop.yml, .github/workflows/Main.yml, .github/workflows/Release.yml, Makefile
=> add evm test

src/components/wallet_mobile/src/rust/account.rs
=> Fix parameters of add_operation_convert_account

.gitignore, src/components/finutils/src/txn_builder/mod.rs
=> Fix algo for FRA fee estimation for some corner cases

src/components/config/src/abci/mod.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/store/api_cache.rs, src/ledger/src/store/mod.rs
=> Tm wasm fix

src/components/finutils/src/bins/fn.rs, src/components/finutils/src/bins/fn.yml, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs, src/ledger/src/store/api_cache.rs, src/ledger/src/store/mod.rs
=> Adding a new CLI command to check balance amount and spent status for

src/components/config/src/abci/mod.rs
Add more error information in config .
Because of the conditional compilation(eg: cfg[..]), ruc error would indicate a incorrect line, this pr would give out more information about the error.
=> Get more error infomation in config.

src/ledger/src/store/api_cache.rs, src/ledger/src/store/mod.rs
=> Fix owned UTXOs panic

src/components/finutils/src/bins/fn.rs, src/components/finutils/src/bins/fn.yml, src/components/finutils/src/common/mod.rs, tools/regression/triple_masking/test_triple_masking.sh, tools/triple_masking/abar_to_bar_convert.sh, tools/triple_masking/assets_mixing_test_demo.sh, tools/triple_masking/bar_to_abar_convert.sh, tools/triple_masking/multi_axfr_test_demo.sh
=> Fix asset mixing abar demo

src/components/finutils/src/txn_builder/mod.rs
=> fix dummy output count in fee estimation

src/components/contracts/modules/evm/contracts/PrismXXBridge.abi.json, src/components/contracts/modules/evm/precompile/sha3fips/src/lib.rs, src/components/contracts/modules/evm/test-vector-support/src/lib.rs, src/components/finutils/src/bins/fn.rs, src/components/finutils/src/common/mod.rs, src/components/finutils/src/txn_builder/mod.rs, src/components/wallet_mobile/README.md, src/ledger/src/data_model/effects.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/store/mod.rs, tools/regression/triple_masking/test_triple_masking.sh, tools/triple_masking/abar_to_bar_convert.sh, tools/triple_masking/anonxfr_test_demo.sh, tools/triple_masking/bar_to_abar_convert.sh, tools/triple_masking/multi_axfr_test_demo.sh
=> Code doc for anon xfr and fee, CLI test scripts fixes and refactoring

src/components/abciapp/src/abci/server/callback/mod.rs, src/components/contracts/baseapp/src/lib.rs, src/components/contracts/baseapp/src/modules.rs, src/components/contracts/modules/evm/Cargo.toml, src/components/contracts/modules/evm/src/lib.rs, src/components/contracts/modules/evm/src/runtime/runner.rs, src/components/contracts/modules/evm/src/utils.rs, src/components/contracts/rpc/src/eth.rs
Generete a transaction when system call prismxx bridge contract.
=> Generate a transaction when system call prismxx bridge contract.

src/components/abciapp/src/api/query_server/query_api/ledger_api.rs, src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/abciapp/src/api/submission_server/submission_api.rs, src/components/config/src/abci/mod.rs, src/components/contracts/baseapp/src/app.rs, src/components/contracts/modules/evm/Cargo.toml, src/components/finutils/src/api/mod.rs, src/components/finutils/src/txn_builder/mod.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/staking/mod.rs, src/ledger/src/store/api_cache.rs, src/ledger/src/store/mod.rs, src/libs/bitmap/src/lib.rs, src/libs/bitmap/src/test.rs, src/libs/cryptohash/src/lib.rs, src/libs/merkle_tree/src/lib.rs
1. api_cache fix
2. clippy fix
=> Fix apicache update

src/components/finutils/src/common/mod.rs, src/components/wasm/src/wasm.rs
=> Add from_string method for txn builder.

src/ledger/src/store/mod.rs
Tmp hot patch, will update use `spent_abars` in `feat-columbus-v1`
=> add the unspent nullifier check

Cargo.toml
=> patch deps version

src/components/finutils/src/bins/fn.rs, src/components/finutils/src/bins/fn.yml, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs, src/components/finutils/src/txn_builder/mod.rs, src/components/wasm/src/wasm.rs, src/ledger/src/data_model/effects.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/store/api_cache.rs, src/ledger/src/store/mod.rs, tools/triple_masking/abar_to_bar_convert.sh
=> Feat fee refactor

src/components/contracts/modules/evm/src/runtime/runner.rs
=> Fix error of prism

src/components/finutils/src/bins/fn.yml
https://github.com/FindoraNetwork/platform/blob/29b44a5ab8a385c5d72c281b67ba8187d29fb65b/src/components/finutils/src/bins/fn.yml#L600
=> Fix: remove abar2bar to-wallet-address required

src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/config/src/abci/mod.rs
=> format code and remove panic

src/ledger/src/store/mod.rs
=> Tracing merkle root

src/components/wasm/src/wasm.rs, src/components/wasm/src/wasm_data_model.rs
=> Fix wasm add output for Abar transfer

Cargo.toml, src/ledger/src/store/mod.rs
=> update to new merkle root

src/components/finutils/src/bins/fn.yml, tools/regression/triple_masking/test_triple_masking.sh, tools/triple_masking/abar_to_bar_convert.sh, tools/triple_masking/anonxfr_test_demo.sh, tools/triple_masking/assets_mixing_test_demo.sh, tools/triple_masking/bar_to_abar_convert.sh, tools/triple_masking/multi_axfr_test_demo.sh
=> Support hyphen in cli

src/ledger/src/store/api_cache.rs, src/ledger/src/store/mod.rs
=> Fix vulnerability by removing some unwrap.

src/components/abciapp/src/abci/mod.rs, src/components/abciapp/src/abci/server/callback/mod.rs, src/components/abciapp/src/bins/abcid.rs
Sleep thread to prevent begin block when exiting.
fix bug in ctrlc handler.
=> Move IN_SAFE_ITV to commit section and fix bug on using of it (main).

src/components/config/src/abci/mod.rs, src/ledger/src/staking/mod.rs
=> feat checkpoint by fix unpaid delegation

src/components/abciapp/Cargo.toml, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/modules/evm/Cargo.toml, src/components/contracts/primitives/mocks/Cargo.toml, src/components/contracts/primitives/types/Cargo.toml, src/components/finutils/Cargo.toml, src/components/finutils/src/bins/fn.rs, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs, src/components/finutils/src/txn_builder/mod.rs, src/components/wallet_mobile/Cargo.toml, src/components/wasm/Cargo.toml, src/components/wasm/src/wasm.rs, src/ledger/Cargo.toml, src/ledger/src/data_model/effects.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/store/api_cache.rs, src/ledger/src/store/mod.rs, src/libs/credentials/Cargo.toml, src/libs/globutils/Cargo.toml, src/libs/sparse_merkle_tree/Cargo.toml
=> Asset record new proof

src/components/finutils/Cargo.toml, src/components/finutils/src/common/utils.rs, src/components/finutils/src/txn_builder/mod.rs
=> add tx hash output for tx send.

Cargo.toml, src/components/abciapp/Cargo.toml, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/modules/evm/Cargo.toml, src/components/contracts/primitives/mocks/Cargo.toml, src/components/contracts/primitives/types/Cargo.toml, src/components/finutils/Cargo.toml, src/components/wallet_mobile/Cargo.toml, src/components/wasm/Cargo.toml, src/ledger/Cargo.toml, src/libs/credentials/Cargo.toml, src/libs/globutils/Cargo.toml, src/libs/sparse_merkle_tree/Cargo.toml
=> update zei version to patch

src/components/abciapp/src/abci/server/callback/utils.rs, src/components/abciapp/src/api/query_server/query_api/ledger_api.rs, src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/finutils/src/bins/fn.rs, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs, src/components/finutils/src/txn_builder/mod.rs, src/components/wasm/src/wasm.rs, src/components/wasm/src/wasm_data_model.rs, src/ledger/Cargo.toml, src/ledger/src/data_model/mod.rs, src/ledger/src/store/mod.rs, src/ledger/src/store/test.rs, src/libs/cryptohash/src/lib.rs, src/libs/globutils/Cargo.toml, src/libs/globutils/src/wallet.rs, src/libs/sparse_merkle_tree/Cargo.toml, src/libs/sparse_merkle_tree/src/lib.rs
=> Wallet transactions page support

src/components/finutils/src/common/mod.rs, src/components/finutils/src/txn_builder/mod.rs, src/libs/globutils/src/wallet.rs
=> Hotfix nullifier from base64 to base58

src/components/config/src/abci/mod.rs, src/components/contracts/baseapp/src/modules.rs, src/components/contracts/modules/ethereum/src/lib.rs, src/components/contracts/modules/ethereum/tests/ethereum_integration.rs, src/components/contracts/modules/evm/tests/evm_integration.rs, src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/core/src/transaction.rs, tools/devnet/env.sh
https://github.com/FindoraNetwork/platform/commit/b0b98034a87b0e3ca762496a0614d2267e469bb8
=> FO-968: Increment Nonce for CheckTx run mode without executing EVM transaction PORT TO MAIN

src/components/abciapp/src/api/query_server/query_api/ledger_api.rs, src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/finutils/src/common/utils.rs
=> fix commitment encode in rpc

src/components/finutils/src/common/mod.rs, src/components/wasm/Cargo.toml, src/components/wasm/src/wasm.rs
=> added utility to convert base64 to base58 in wasm

.github/workflows/Develop.yml, .github/workflows/Features.yml, .github/workflows/Main.yml, .github/workflows/Others.yml, .github/workflows/Release.yml, .github/workflows/WasmCat.yml, container/Dockerfile-binary-image-dev, container/Dockerfile-binary-image-release
=> add new runner

src/components/abciapp/src/abci/server/callback/mod.rs, src/components/config/src/abci/mod.rs, src/components/finutils/src/bins/fn.rs, src/components/finutils/src/common/mod.rs, src/components/finutils/src/txn_builder/mod.rs, src/ledger/src/data_model/effects.rs, src/ledger/src/store/mod.rs, tools/regression/evm/scripts/setup.sh, tools/regression/triple_masking/asset_mixing_test.sh
=> Tm checkpoint

src/components/finutils/Cargo.toml, src/components/finutils/src/common/utils.rs, src/components/finutils/src/txn_builder/mod.rs, src/components/wasm/src/wasm.rs
=> add seed argument to support store commitment

src/ledger/Cargo.toml
=> fix creating checkpoint file by debug_env.

src/components/abciapp/src/api/query_server/query_api/ledger_api.rs
Query of getting owned utxos will not panic if it failed.
=> Fix panic of geting utxo.

src/components/abciapp/src/abci/server/callback/mod.rs, src/components/config/src/abci/mod.rs, src/components/finutils/src/common/evm.rs, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/store/utils.rs
Fix the problem of utxo transaction body without signature
=> fix tx sign

.github/PULL_REQUEST_TEMPLATE.md, src/components/contracts/rpc/src/lib.rs, src/libs/merkle_tree/src/lib.rs
=> Update PR template: main

.github/PULL_REQUEST_TEMPLATE.md
=> Update pr template: develop

src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/abciapp/src/api/query_server/query_api/server.rs, src/components/config/src/abci/mod.rs, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs, src/ledger/src/data_model/effects.rs, src/ledger/src/store/api_cache.rs, src/ledger/src/store/helpers.rs, src/ledger/src/store/test.rs, src/ledger/src/store/utils.rs
=> fix asset prefix

src/components/abciapp/src/abci/server/callback/mod.rs
=> fix prism exec code

src/components/finutils/src/txn_builder/mod.rs, src/components/wasm/src/wasm.rs
This is to handle building, signing and serialization properly in SDK.
=> Moving txn building to separate method from serialization in WASM.

src/components/wasm/Cargo.toml, src/components/wasm/src/wasm.rs
=> Wasm new asset code

Cargo.toml, src/components/contracts/baseapp/Cargo.toml, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/modules/ethereum/Cargo.toml, src/components/contracts/modules/evm/Cargo.toml, src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/storage/Cargo.toml, src/ledger/Cargo.toml, src/libs/sparse_merkle_tree/Cargo.toml
=> upgrade storage and zei version

Makefile, tools/devnet/env.sh, tools/devnet/resetnodes.sh, tools/devnet/snapshot.sh, tools/regression/evm.py, tools/regression/evm/scripts/setup.sh, tools/regression/evm/testevm.sh
1. Added env variable for endpoint
2. Used env variable for BIN path
3. Created new target for evmtest under nightly build
4. Added verification logic after balance verification command
=> FO-1059: EVM integration tests adjustment for Nightly

tools/devnet/env.sh
1. Allow integration tests taking custom env variables.
=> Use custom env variables if specified

src/ledger/src/data_model/effects.rs, src/ledger/src/store/api_cache.rs, src/ledger/src/store/test.rs
=> changing asset code to derived asset code inside Asset object on chain

tools/devnet/cleannodes.sh, tools/devnet/confignodes.sh, tools/devnet/resetnodes.sh, tools/regression/evm/testevm.sh
=> fix make debug_env and make evmtest

.github/workflows/Nightly.yml
- update the tag name to date
- update the checkout version to v3 to accept ref
the nightly workflow can not checkout the specific branch. Update the checkout to version v3  can fix this issue. 
=> update Nightly build workflow

tools/devnet/confignodes.sh
Makes the `make devnet` command work on Mac
=> fix confignodes bashscript for OSX

src/components/abciapp/src/api/query_server/query_api/server.rs, src/ledger/src/store/api_cache.rs, src/ledger/src/store/mod.rs, src/ledger/src/store/test.rs
=> remove some unwrap.

src/components/contracts/modules/account/src/impls.rs
=> fix bug create contract failed by another contract

src/components/config/src/abci/mod.rs, src/ledger/src/data_model/effects.rs, src/ledger/src/store/mod.rs, src/ledger/src/store/test.rs
Fix the bug that the prefix added to `AssetTypeCode`is not compatible with historical data
=> fix logic bug for asset type code prefix

tools/devnet/snapshot.sh
1. Make devnet as fast as possible.
=> make devnet faster

src/components/contracts/modules/account/src/impls.rs, src/components/finutils/src/txn_builder/mod.rs, src/components/wasm/src/wasm.rs
=> Fix pointer borrow in wasm for abar operations

src/components/contracts/baseapp/Cargo.toml, src/components/contracts/baseapp/src/lib.rs, src/components/contracts/baseapp/src/modules.rs, src/components/contracts/primitives/types/src/actions/xhub.rs
=> fix logic for prism to compact apphash mismatch

src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/config/src/abci/mod.rs
=> add display checkpoint rpc

Cargo.toml
=> New ZEI version

.github/workflows/Nightly.yml, Makefile, container/Dockerfile-binary-rust-base, tools/download_tendermint.sh
=> Download tendermint release in makefile

src/components/contracts/modules/evm/precompile/frc20/src/lib.rs, src/components/contracts/primitives/rpc-core/src/types/account_info.rs, src/components/contracts/primitives/rpc-core/src/types/call_request.rs, src/components/contracts/primitives/rpc-core/src/types/filter.rs, src/components/contracts/primitives/rpc-core/src/types/index.rs, src/components/contracts/primitives/rpc-core/src/types/sync.rs, src/components/contracts/primitives/rpc-core/src/types/transaction.rs, src/libs/cryptohash/src/lib.rs
=> fix lint on main branch

src/components/abciapp/Cargo.toml, src/components/config/Cargo.toml, src/components/config/src/abci/mod.rs
=> update btm crate version

src/components/contracts/baseapp/src/app.rs, src/components/contracts/baseapp/src/lib.rs, src/components/contracts/modules/ethereum/src/impls.rs, src/components/contracts/modules/ethereum/src/lib.rs, src/components/contracts/primitives/core/src/context.rs, src/components/contracts/rpc/Cargo.toml, src/components/contracts/rpc/src/lib.rs, src/libs/cryptohash/src/lib.rs
1. add recover_signer_fast to reduce expensive function calls
=> Tps main v6

checkpoint_devnet_example.toml, src/components/finutils/src/bins/fn.yml, tools/regression/triple_masking/asset_mixing_test.sh
=> fn handle assets with hyphen & update checkpoint example

.gitignore, src/components/contracts/modules/ethereum/src/impls.rs, src/components/contracts/primitives/core/src/context.rs, src/ledger/src/data_model/effects.rs, src/libs/merkle_tree/src/lib.rs
=> fmt code; ignore checkpoint files(generated by tests)

src/components/abciapp/Cargo.toml, src/components/abciapp/src/api/query_server/query_api/mod.rs
=> Display checkpoint add  bridge address

src/components/abciapp/src/api/query_server/query_api/mod.rs
=> fix logic of show system contract on checkpoint

.github/PULL_REQUEST_TEMPLATE.md
Added manual Nightly criteria to PR template
=> Added manual nightly criteria to PR template

.gitignore
add checkpoint* to .gitignore.
=> Ignore checkpoint.toml.

src/components/finutils/src/txn_builder/mod.rs, src/components/wasm/src/wasm.rs
Manual Nightly passed: https://jenkins.dev.findora.org/view/integration%20test/job/Manual%20Integration%20Test/30/
=> FO-1145: Feat anon fee estimate

src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs
Fix api `get_created_assets` return value problem
fn 
api
=> fix api for `get_created_assets`

Makefile, tools/devnet/env.sh, tools/regression/evm/scripts/setup.sh, tools/regression/triple_masking/scripts/setup.sh
=> added rls target for Nightly and slightly adjusted network setup

src/components/finutils/src/bins/stt/stt.rs
=> fix stt init 

src/components/abciapp/src/abci/server/callback/mod.rs, src/components/abciapp/src/abci/staking/mod.rs, src/components/config/src/abci/mod.rs, src/ledger/src/staking/mod.rs
=> fix undelegation missing reward.

src/components/abciapp/src/abci/server/callback/mod.rs, src/components/abciapp/src/abci/staking/mod.rs
The payment of prism tx is advanced from end_block to deliver_tx
=> fix prism tx mint pay

.gitignore, Makefile, src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/config/src/abci/mod.rs, src/components/config/src/findora/mod.rs, tools/download_tendermint.sh, tools/fmt.sh, tools/node_init.sh
ref: https://github.com/FindoraNetwork/tendermint/commit/348cc4b6d306037a38cb0574469362ead9805c95
=> fix compilation on MacOS and `make join_qa0N`

src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/abciapp/src/api/query_server/query_api/server.rs
=> adding a new API to query server for Max ATxo SID

Cargo.toml, src/components/contracts/baseapp/Cargo.toml, src/components/contracts/baseapp/src/lib.rs, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/modules/account/src/tests.rs, src/components/contracts/modules/ethereum/Cargo.toml, src/components/contracts/modules/ethereum/tests/ethereum_db.rs, src/components/contracts/modules/evm/Cargo.toml, src/components/contracts/modules/evm/precompile/Cargo.toml, src/components/contracts/modules/evm/src/lib.rs, src/components/contracts/modules/evm/src/runtime/stack.rs, src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/core/src/transaction.rs, src/components/contracts/primitives/storage/Cargo.toml, src/ledger/Cargo.toml, src/libs/sparse_merkle_tree/Cargo.toml
* **make sure that you have executed below Jenkins jobs successfully**
https://jenkins.dev.findora.org/view/integration%20test/job/Manual%20Integration%20Test/65/
https://jenkins.dev.findora.org/view/integration%20test/job/Manual-Platform-test/21/
=> Tps main v7 for develop

tools/download_tendermint.sh
=> fix the compilation issue of Tendermint on MacOS

Makefile, src/components/config/src/abci/mod.rs, src/components/contracts/rpc/Cargo.toml, src/components/finutils/Cargo.toml, src/components/finutils/src/bins/fn.rs, src/components/finutils/src/bins/fn.yml, src/components/finutils/src/common/dev.rs, src/components/finutils/src/common/dev/README.md, src/components/finutils/src/common/dev/init.rs, src/components/finutils/src/common/dev/mod.rs, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs, src/ledger/Cargo.toml, src/ledger/src/data_model/mod.rs, src/ledger/src/staking/mod.rs
- __This is an upgrade and improvement over older tools like `make debug_env` and `make devnet`__
```
fn-dev
Manage development clusters on your localhost
USAGE:
fn dev [OPTIONS] [SUBCOMMAND]
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
-e, --env-name <ENV NAME>    The name of the target env
SUBCOMMANDS:
add-node    Attach a new node to an existing env
create      Create a new env
del-node    Pop a node from an existing env
destroy     Destroy an existing env
help        Prints this message or the help of the given subcommand(s)
info        Default operation, show the information of an existing env
init …
```
=> advanced managements of local clusters（DevNet）

src/components/contracts/baseapp/src/lib.rs, src/components/contracts/primitives/core/src/macros.rs, src/components/finutils/src/common/dev/mod.rs
=> fix ports mgmt in `fn dev`

src/components/finutils/src/common/dev/mod.rs
=> tuning comments

Makefile, src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/config/src/abci/mod.rs, src/components/contracts/modules/ethereum/src/impls.rs, src/components/contracts/modules/ethereum/src/lib.rs, src/components/contracts/modules/evm/src/lib.rs, src/components/contracts/primitives/core/src/macros.rs, src/components/contracts/rpc/Cargo.toml, src/components/finutils/Cargo.toml, src/components/finutils/src/bins/fn.rs, src/components/finutils/src/bins/fn.yml, src/components/finutils/src/common/dev/README.md, src/components/finutils/src/common/dev/init.rs, src/components/finutils/src/common/dev/mod.rs, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs, src/ledger/Cargo.toml, src/ledger/src/staking/mod.rs
=> port #476 to develop branch

Makefile
=> discard the filter in `make pack` for container compitability

Makefile
=> discard the filter in `make pack` (#492)

src/components/config/src/abci/mod.rs, src/ledger/src/data_model/mod.rs, src/libs/merkle_tree/src/lib.rs, src/libs/sliding_set/src/lib.rs
Fix the implicit bug of array operation in `check_tx`
This issue has been fixed in develop,pr is [375](https://github.com/FindoraNetwork/platform/pull/375)
=> Fix the implementation logic of `check_tx`

src/components/contracts/baseapp/src/lib.rs
=> configure chainstate history through env variable

Makefile, README.md, docs/fn_dev.md, src/components/finutils/src/bins/fn.rs, src/components/finutils/src/bins/fn.yml, src/components/finutils/src/bins/stt/init/mod.rs, src/components/finutils/src/bins/stt/stt.rs, src/components/finutils/src/common/dev/README.md, src/components/finutils/src/common/dev/init.rs, src/components/finutils/src/common/dev/mod.rs, src/ledger/src/staking/mod.rs
=> cherry-pick #504

src/components/finutils/src/bins/fn.rs, src/components/finutils/src/txn_builder/mod.rs, src/components/wasm/src/wasm.rs
=> Address folding wasm

src/components/finutils/src/bins/fn.rs, src/components/finutils/src/bins/fn.yml, src/components/finutils/src/common/dev/README.md, src/components/finutils/src/common/dev/mod.rs
=> tuning some details of `fn dev` (#512)

src/components/finutils/src/common/dev/mod.rs
=> fix ports checker issue in `fn dev create`

src/components/finutils/src/common/dev/mod.rs
* fix the `--force` flag in `fn dev create`
* fix ports checker
=> fix ports checker issue in `fn dev create` (#515)

src/components/abciapp/src/abci/staking/mod.rs, src/components/config/src/abci/mod.rs
=> Modify the validator's validator line to 100

Cargo.toml, src/components/contracts/baseapp/Cargo.toml, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/modules/ethereum/Cargo.toml, src/components/contracts/modules/evm/Cargo.toml, src/components/contracts/modules/evm/precompile/Cargo.toml, src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/storage/Cargo.toml
=> update storage to speedup catch-up

src/components/contracts/primitives/wasm/src/wasm.rs, src/components/wasm/src/wasm.rs, src/components/wasm/src/wasm_data_model.rs
=> Fix missing wasm_bindgen.

src/components/wasm/src/wasm.rs, src/components/wasm/src/wasm_data_model.rs
=> add wasm for public_key_from_base64 and PublicParams.new

src/components/wasm/src/wasm.rs, src/ledger/src/converter/mod.rs
=> fix check for prism convert.

src/components/contracts/primitives/types/src/crypto.rs
refs #520 
refs https://github.com/FindoraNetwork/zei/pull/141
=> revert address34 and compatible with XfrPublicKey

src/components/config/src/abci/mod.rs, src/components/contracts/modules/ethereum/src/lib.rs, src/components/contracts/modules/ethereum/tests/ethereum_integration.rs, src/components/contracts/modules/evm/src/runtime/runner.rs, src/components/contracts/modules/evm/src/runtime/stack.rs, src/components/contracts/modules/evm/tests/utils/erc20.rs, src/components/contracts/primitives/traits/Cargo.toml, src/components/contracts/primitives/traits/src/evm.rs, src/components/contracts/rpc/Cargo.toml, src/components/contracts/rpc/src/eth.rs
=> add interface to set minimal gas price

tools/devnet/stopnodes.sh
=> fix kill signal flag in stopnodes

src/components/contracts/baseapp/src/modules.rs, src/ledger/src/converter/mod.rs
=> Fix converter

src/components/finutils/src/common/dev/mod.rs
=> filter out the node itself when setting persistent peers

src/components/abciapp/src/abci/staking/mod.rs
=> Fix decimal on prismxx

Cargo.toml
=> update zei version

.github/workflows/WasmCat.yml
=> Fix: Wasm CI add tags trigger

src/components/config/src/abci/mod.rs
Comment on `CheckPointConfig`, associate checkpoints with PRs .
Now you can inspect where and when the checkpoint was set.
=> Associate checkpoints with PRs .

src/components/abciapp/src/abci/server/callback/mod.rs, src/components/abciapp/src/abci/staking/mod.rs, src/components/config/src/abci/mod.rs
=> fix app mismatch for qa02

src/components/contracts/primitives/rpc-core/Cargo.toml, src/components/contracts/primitives/rpc-server/Cargo.toml, src/components/contracts/rpc/Cargo.toml
We forked the jsonprc and remove orign check and host check in websocket's handshake, this fix the connection error from frontend.
=> Use forked jsonprc to fix websocket connection error.

.github/workflows/WasmCat.yml
remove the credential from github. All the PR from any fork repo can update wasm.
=> Change wasm runner

.github/workflows/Develop.yml
=> fix the extra quotation mark in CI pipeline 

src/components/contracts/primitives/wasm/Cargo.toml, src/components/finutils/Cargo.toml, src/components/wasm/Cargo.toml, src/libs/credentials/Cargo.toml
=> Rollback wasm-bindgen for main

src/components/finutils/src/common/dev/mod.rs
=> `fn dev`: cors_allowed_origins = ["*"]

.github/workflows/WasmCat.yml, container/Dockerfile-binary-image-dev
=> change the build method to debug in dev env and remove the extra step

.github/workflows/WasmCat.yml
=> remove the tag part

.github/workflows/DevelopArm.yml, .github/workflows/Release.yml, .github/workflows/ReleaseArm.yml, Makefile, container/Dockerfile-binary-image-dev-arm, container/Dockerfile-binary-image-release-arm, container/Dockerfile-binary-rust-base-arm, container/Dockerfile-goleveldb-arm
=> Add findorad arm build

src/components/wasm/src/wasm.rs, src/libs/globutils/Cargo.toml, src/libs/globutils/src/wallet.rs
=> Fix the whitespace issue of the mnemonic phrase parser

Cargo.toml, src/components/contracts/rpc/Cargo.toml, src/components/finutils/Cargo.toml, src/components/wasm/src/wasm.rs, src/ledger/Cargo.toml
This PR is necessary to fix some issues regarding changes in dependency.
=> Update the tendermint version and noah version in develop

Makefile, src/components/finutils/Cargo.toml, src/components/finutils/src/bins/fn.rs, src/components/finutils/src/common/dev/README.md, src/components/finutils/src/common/dev/init.rs, src/components/finutils/src/common/dev/mod.rs
=> re-implement `fn dev` based on the `chaindev` crate

Cargo.toml, src/components/finutils/Cargo.toml, src/components/finutils/src/common/mod.rs
=> fix wasm compilation

docs/fn_ddev.md, src/components/finutils/Cargo.toml, src/components/finutils/src/bins/fn.rs, src/components/finutils/src/bins/fn.yml, src/components/finutils/src/common/ddev/README.md, src/components/finutils/src/common/ddev/init.rs, src/components/finutils/src/common/ddev/mod.rs, src/components/finutils/src/common/dev/README.md, src/components/finutils/src/common/mod.rs
.
.
.
**Distributed version of `fn dev`.**
.
.
.
=> implement `fn ddev`

src/components/abciapp/src/api/query_server/query_api/server.rs, src/ledger/src/store/api_cache.rs
=> Fix Max ATxo APIs to return null for no abars

src/components/finutils/Cargo.toml, src/components/finutils/src/common/ddev/init.rs, src/components/finutils/src/common/ddev/mod.rs
=> fix `fn ddev init`

container/Dockerfile-binary-rust-base, container/Dockerfile-binary-rust-base-arm
=> update rust to 1.64.0

src/components/abciapp/Cargo.toml, src/components/abciapp/src/abci/mod.rs, src/components/abciapp/src/abci/server/callback/mod.rs, src/components/config/Cargo.toml, src/components/config/src/findora/mod.rs, src/ledger/src/lib.rs
=> sub-PR of #688: optimize details

Cargo.toml
=> FO-1345: Tag our arkworks-rs forks

CHANGELOG.md
Update evm changelog for v0.3.30-release
=> update evm changelog for v0.3.30-release

.github/workflows/RPCNode.yml, Makefile, container/Dockerfile-enterprise-web3
=> fix build maketile issue

src/components/abciapp/src/abci/server/callback/mod.rs, src/components/abciapp/src/abci/staking/mod.rs, src/components/config/src/abci/mod.rs, src/components/contracts/modules/evm/contracts/PrismXXBridge.abi.json, src/components/contracts/modules/evm/src/utils.rs
=> fix prism decimal for nft

src/components/config/src/abci/mod.rs
=> upgrade height for release-0.3.30

src/components/config/src/abci/mod.rs
=> update height for 0.3.30

src/ledger/src/data_model/mod.rs
=> fix app hash mismatch for sync old version

Cargo.toml, Makefile, container/Dockerfile-enterprise-web3, src/components/abciapp/Cargo.toml, src/components/abciapp/src/abci/server/callback/mod.rs, src/components/contracts/baseapp/Cargo.toml, src/components/contracts/baseapp/src/app.rs, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/modules/account/src/impls.rs, src/components/contracts/modules/account/src/lib.rs, src/components/contracts/modules/ethereum/Cargo.toml, src/components/contracts/modules/ethereum/src/impls.rs, src/components/contracts/modules/evm/Cargo.toml, src/components/contracts/modules/evm/src/lib.rs, src/components/contracts/modules/evm/src/runtime/runner.rs, src/components/contracts/modules/evm/src/runtime/stack.rs, src/components/contracts/primitives/enterprise-web3/Cargo.toml, src/components/contracts/primitives/enterprise-web3/src/lib.rs, src/components/finutils/Cargo.toml
=> Enterprise web3 to develop

src/ledger/src/data_model/effects.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/store/mod.rs
=> Fix serde error of signmap for sync old version

src/components/finutils/src/common/mod.rs
=> trim seckey in `fn` for friendly usage

src/components/finutils/src/bins/stt/stt.rs
=> Fix stt init.

Makefile, src/components/abciapp/src/abci/server/callback/mod.rs, src/components/contracts/baseapp/src/app.rs, src/components/contracts/primitives/enterprise-web3/Cargo.toml, src/components/contracts/primitives/enterprise-web3/src/lib.rs
=> add r2d2 redis pool

Makefile, src/components/finutils/Cargo.toml
- remove dup entries in `Makefile`
- bump deps
=> bump chaindev

Makefile
=> Fix makefile in main

src/components/abciapp/src/abci/server/callback/mod.rs, src/components/contracts/baseapp/src/app.rs, src/components/contracts/primitives/enterprise-web3/Cargo.toml, src/components/contracts/primitives/enterprise-web3/src/lib.rs
=> add r2d2 redis pool to develop

Makefile
=> remove the image tag latest from release build process

src/components/contracts/rpc/src/eth.rs
=> update EVM_FIRST_BLOCK_HEIGHT to checkpoint

Makefile, docs/benchmarks/README.md, docs/benchmarks/evm.md, tools/benchutils/bench.sh
=> tuning benchmark scripts

src/components/abciapp/src/abci/staking/test.rs, src/components/abciapp/src/api/query_server/query_api/ledger_api.rs, src/components/contracts/modules/evm/tests/utils/solidity.rs, src/components/contracts/primitives/mocks/src/lib.rs, src/components/contracts/primitives/types/src/crypto.rs, src/components/contracts/primitives/utils/src/ecdsa.rs, src/components/contracts/primitives/utils/src/lib.rs, src/components/contracts/primitives/wasm/src/wasm.rs, src/components/contracts/rpc/src/eth_pubsub.rs, src/components/finutils/src/bins/stt/init/i_testing.rs, src/components/finutils/src/common/utils.rs, src/ledger/src/data_model/test.rs, src/ledger/src/staking/cosig.rs, src/ledger/src/staking/mod.rs, src/ledger/src/store/api_cache.rs, src/ledger/src/store/mod.rs, src/libs/bitmap/src/lib.rs, src/libs/globutils/src/wallet.rs, src/libs/merkle_tree/src/lib.rs, src/libs/sliding_set/src/lib.rs
=> fix new lints when using rust 1.66

docs/benchmarks/evm.md, tools/benchutils/bench.sh
=> update benchmark samples

src/components/abciapp/src/abci/staking/test.rs, src/components/abciapp/src/api/query_server/query_api/ledger_api.rs, src/components/contracts/baseapp/src/tm_events.rs, src/components/contracts/modules/evm/tests/utils/solidity.rs, src/components/contracts/primitives/mocks/src/lib.rs, src/components/contracts/primitives/types/src/crypto.rs, src/components/contracts/primitives/utils/src/ecdsa.rs, src/components/contracts/primitives/utils/src/lib.rs, src/components/contracts/primitives/wasm/src/wasm.rs, src/components/contracts/rpc/src/eth_pubsub.rs, src/components/contracts/rpc/src/web3.rs, src/components/finutils/src/bins/stt/init/i_testing.rs, src/components/finutils/src/common/utils.rs, src/components/finutils/src/txn_builder/mod.rs, src/components/wallet_mobile/src/rust/account.rs, src/ledger/src/data_model/test.rs, src/ledger/src/staking/cosig.rs, src/ledger/src/staking/mod.rs, src/ledger/src/store/api_cache.rs, src/ledger/src/store/mod.rs, src/libs/bitmap/src/lib.rs, src/libs/globutils/src/wallet.rs, src/libs/merkle_tree/src/lib.rs, src/libs/sliding_set/src/lib.rs
Fixed all clippy related errors after latest rust tools update.
=> Fix errors after clippy updatd

src/ledger/src/data_model/effects.rs
Since we may have some changes to the tracing systems in the future, we here first block confidential transfer with tracing policies, on the networks.
=> Block confidential transfer with tracing policies

src/components/config/src/abci/mod.rs, src/components/contracts/modules/evm/precompile/Cargo.toml, src/components/contracts/modules/evm/precompile/frc20/Cargo.toml, src/components/contracts/modules/evm/precompile/frc20/src/lib.rs, src/components/contracts/modules/evm/precompile/src/lib.rs
=> remove delegatecall support

container/Dockerfile-fn-musl-macos, container/Dockerfile-fn-musl-macos-base
=> fix build macos fn

src/components/wasm/src/wasm.rs
=> add wasm get key old to develop

src/components/wasm/src/wasm.rs, src/libs/globutils/src/wallet.rs
=> add wasm metamask account

container/Dockerfile-fn-musl-macos, container/Dockerfile-fn-musl-macos-base
=> fix build macos fn to develop

src/components/wasm/src/wasm.rs
=> add wasm get_keypair_by_pri_key

.dockerignore, .github/workflows/Fn_Check.yml, .github/workflows/WasmCat.yml, container/Dockerfile-debug-env, tools/devnet/startnodes.sh, tools/fn_check.sh
=> Feat: Add Main Branch Fn Check CI

src/components/wasm/src/wasm.rs
=> add wasm bech32_to_base64_old

src/components/wasm/src/wasm.rs
=> add wasm new_keypair_old

src/components/abciapp/Cargo.toml, src/components/abciapp/src/abci/server/callback/mod.rs, src/components/abciapp/src/abci/staking/mod.rs, src/components/config/src/abci/mod.rs, src/components/contracts/baseapp/Cargo.toml, src/components/contracts/baseapp/src/lib.rs, src/components/contracts/baseapp/src/modules.rs, src/components/contracts/modules/evm/contracts/PrismXXBridge.abi.json, src/components/contracts/modules/evm/src/lib.rs, src/components/contracts/modules/evm/src/system_contracts.rs, src/components/contracts/modules/evm/src/utils.rs, src/components/wasm/src/wasm.rs
=> Upgrade prism

Makefile, container/Dockerfile-binary-image-release, container/Dockerfile-binary-rust-base, container/Dockerfile-goleveldb, container/docker-entrypoint-findorad.sh, container/rosetta.sh
It will add a Rosetta API into every findorad image and run it when container start. 
=> Add rosetta to findorad image

README.md
=> fix badges for build

.github/workflows/RPCNode.yml, .github/workflows/RPCNodeRelease.yml, .github/workflows/RPCNodeTest.yml
=> combine RPCNode into release tag

src/components/config/src/abci/mod.rs
=> prism bridge asdress update

src/components/config/src/abci/mod.rs, src/components/contracts/modules/ethereum/src/impls.rs, src/components/contracts/modules/ethereum/src/lib.rs, src/components/contracts/primitives/core/src/transaction.rs, tools/devnet/startnodes.sh
Fix two following issues:
1. Transaction receipt is missing when EVM returns error code 1
2. Nonce is not increased on revert.
=> Fix reentrant hang issue

src/components/wasm/src/wasm.rs
=> fix wasm return

src/components/abciapp/Cargo.toml, src/components/abciapp/src/abci/server/callback/mod.rs, src/components/abciapp/src/abci/staking/mod.rs, src/components/contracts/modules/evm/src/lib.rs, src/components/contracts/modules/evm/src/utils.rs, src/components/contracts/primitives/types/src/actions/xhub.rs, src/components/finutils/src/common/evm.rs, src/components/wasm/src/wasm.rs, src/ledger/src/store/mod.rs
=> fix prismxx init

container/Dockerfile-binary-image-dev
=> fix the bightly build issue. add rosetta build process to dev

src/components/config/src/abci/mod.rs, src/components/contracts/modules/ethereum/src/impls.rs, src/components/contracts/modules/ethereum/src/lib.rs, src/components/contracts/primitives/core/src/transaction.rs
* fix unhandled transaction
* fix evm deliver_tx nonce
* update startnodes.sh and checkpoint file
---------
=> Fix reentrant hang issue (#707)

container/docker-entrypoint-findorad.sh, src/components/config/src/abci/mod.rs, src/components/finutils/src/bins/cfg_generator.rs, src/components/finutils/src/common/mod.rs, src/libs/merkle_tree/src/lib.rs, tools/benchutils/bench.sh, tools/fn_check.sh, tools/node_init.sh
- make `make join_mainnet` avaliable on current develop branch
- support custom data path, eg: ` TENDERMINT_HOME=/tmp/mainnet make join_mainnet`
- `make fmtall`
=> make the `develop` branch compatible with current mainnet

src/components/abciapp/src/abci/server/callback/mod.rs
=> fix check_signatures_num

.github/workflows/Develop.yml, .github/workflows/Main.yml, .github/workflows/Nightly.yml, .github/workflows/RPCNodeRelease.yml, .github/workflows/Release.yml
=> change docker login method

src/components/config/src/findora/mod.rs, src/components/contracts/primitives/rpc-core/src/types/block_number.rs, src/components/contracts/primitives/rpc-core/src/types/pubsub.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/staking/mod.rs
=> fix clippy

CHANGELOG.md
Update change log for v0.3.38-release
=> Update change log for v0.3.38-release

CHANGELOG.md, src/components/contracts/modules/evm/src/runtime/stack.rs
=> fix build web3 and add changelog

tools/download_tendermint.sh
=> fix tendermint LoadBlock

src/components/config/src/abci/mod.rs, src/ledger/src/data_model/effects.rs
=> fix check replay

src/components/contracts/modules/ethereum/src/impls.rs, src/components/contracts/rpc/src/eth.rs
=> fix error of rpc query index out of bound

src/components/contracts/modules/evm/precompile/Cargo.toml, src/components/contracts/modules/evm/precompile/anemoi/Cargo.toml, src/components/contracts/modules/evm/precompile/anemoi/benches/anemoi.rs, src/components/contracts/modules/evm/precompile/anemoi/src/lib.rs, src/components/contracts/modules/evm/precompile/basic/Cargo.toml, src/components/contracts/modules/evm/precompile/basic/benches/sha256.rs, src/components/contracts/modules/evm/precompile/src/lib.rs, src/components/finutils/src/common/mod.rs, src/components/wasm/src/wasm.rs, src/ledger/Cargo.toml, src/ledger/src/data_model/mod.rs, src/ledger/src/store/api_cache.rs, src/ledger/src/store/helpers.rs, src/ledger/src/store/mod.rs
=> Add the Anemoi precompile and change the asset hashing

src/components/finutils/src/common/evm.rs, src/components/finutils/src/common/mod.rs
=> fix fn contract-deposit

src/ledger/src/data_model/mod.rs, src/ledger/src/store/mod.rs
=> fix AssetTypePrefix

src/ledger/src/converter/mod.rs
=> fix lowlevel_data

.github/workflows/RPCNodeTest.yml, container/Dockerfile-enterprise-web3
=> Fix the release tag can not correctly build the RPC image

src/components/contracts/modules/ethereum/src/impls.rs
主网出现相同合约code，相同交易，合约执行完成后，receipt中的log里面的data不一致，经查询发现是由于
https://github.com/FindoraNetwork/platform/pull/841  将  https://github.com/FindoraNetwork/platform/pull/117 返回的错误信息加到log中，导致每个节点的log信息不一致，在receipt的log中去掉返回的错误信息
=> fix  evm log

src/components/abciapp/Cargo.toml, src/components/abciapp/src/abci/server/callback/mod.rs, src/components/abciapp/src/bins/findorad.rs, src/components/config/src/abci/mod.rs, src/components/config/src/findora/mod.rs, src/components/contracts/baseapp/Cargo.toml, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/modules/account/src/impls.rs, src/components/contracts/modules/ethereum/Cargo.toml, src/components/contracts/modules/ethereum/src/impls.rs, src/components/contracts/modules/evm/Cargo.toml, src/components/wallet_mobile/src/rust/account.rs
=> update enterprise_web3 feature to cli

Cargo.toml, src/components/finutils/src/bins/stt/stt.rs, src/components/finutils/src/txn_builder/mod.rs, src/ledger/Cargo.toml, src/ledger/src/data_model/effects.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/store/mod.rs
=> Use the final revision of the Noah branch

Cargo.toml, src/components/finutils/src/txn_builder/mod.rs, src/ledger/Cargo.toml, src/ledger/src/data_model/effects.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/store/mod.rs
=> Renew #935 for merging develop with main.

src/components/wasm/Cargo.toml, src/components/wasm/src/wasm.rs
=> Add init noah wasm32 

src/components/abciapp/src/abci/mod.rs, src/components/abciapp/src/abci/server/callback/mod.rs, src/ledger/src/converter/mod.rs
=> fix fn exec

src/components/abciapp/Cargo.toml, src/components/abciapp/src/bins/findorad.rs, src/components/config/src/abci/mod.rs
=> fix config time and update checkpoint

src/components/finutils/src/txn_builder/mod.rs
=> Fix abar_to_ar params

src/components/contracts/baseapp/Cargo.toml, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/modules/ethereum/Cargo.toml, src/components/contracts/modules/evm/Cargo.toml, src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/storage/Cargo.toml
=> storage performance optimize

tools/download_tendermint.sh
=> patch tendermint from pr 5141 and 6204

container/Dockerfile-wallet_mobile-lib_android, src/components/wallet_mobile/src/android/tx_builder.rs, src/components/wallet_mobile/src/ios/tx_builder.rs, src/components/wallet_mobile/src/rust/account.rs
=> mobile lib add prism param

src/components/abciapp/src/abci/staking/mod.rs, src/components/abciapp/src/bins/findorad.rs, src/components/config/src/abci/mod.rs
=> fix staking validator offline

src/components/abciapp/src/abci/staking/mod.rs
=> remove VALIDATOR_LIMIT_V3

src/components/contracts/modules/evm/precompile/anemoi/Cargo.toml, src/ledger/Cargo.toml
=> Update noah version

container/Dockerfile-wallet_mobile-lib_android, src/components/config/src/abci/mod.rs, src/components/wallet_mobile/src/android/tx_builder.rs, src/components/wallet_mobile/src/rust/account.rs
=> fix mibile core dump and fix sign and update checkpoint

src/components/abciapp/Cargo.toml
=> downgrade ctrlc

src/components/abciapp/src/bins/findorad.rs
=> update timeout_propose 3s

src/components/contracts/baseapp/src/extensions.rs
=> fix develop build

src/components/wallet_mobile/src/android/exception.rs, src/components/wallet_mobile/src/android/mod.rs
=> android add execption

src/components/abciapp/src/abci/staking/mod.rs, src/components/config/src/abci/mod.rs
=> validator whitelist v3

src/components/contracts/modules/evm/precompile/src/lib.rs
This PR suspends the EIP 1962 from the develop branch for now.
=> EIP 1962 is undecided.

src/components/finutils/Cargo.toml
=> fix build develop wasm

Makefile
=> fix macos fn path isuse

container/Dockerfile-wallet_mobile-lib_android, src/components/wallet_mobile/src/android/tx_builder.rs, src/components/wallet_mobile/src/ios/free.rs, src/components/wallet_mobile/src/ios/mod.rs, src/components/wallet_mobile/src/ios/tx_builder.rs
=> Fix mobile build

Cargo.toml, src/components/abciapp/src/api/query_server/query_api/ledger_api.rs, src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/abciapp/src/api/query_server/query_api/server.rs, src/components/finutils/Cargo.toml, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs, src/ledger/Cargo.toml, src/ledger/src/data_model/mod.rs, src/ledger/src/store/api_cache.rs
Reverts FindoraNetwork/platform#1012
=> Revert "clear api"

src/components/abciapp/src/abci/server/callback/mod.rs, src/components/contracts/baseapp/src/lib.rs, src/components/contracts/baseapp/src/modules.rs, src/components/contracts/modules/evm/src/lib.rs, src/ledger/Cargo.toml
=> fix evm findora_tx hash

src/components/abciapp/src/abci/mod.rs, src/components/abciapp/src/abci/server/callback/mod.rs, src/components/abciapp/src/abci/server/mod.rs, src/components/contracts/baseapp/Cargo.toml, src/components/contracts/baseapp/src/lib.rs, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/modules/account/src/tests.rs, src/components/contracts/modules/ethereum/Cargo.toml, src/components/contracts/modules/ethereum/tests/ethereum_db.rs, src/components/contracts/modules/evm/Cargo.toml, src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/storage/Cargo.toml, src/components/contracts/primitives/storage/src/tests.rs, src/ledger/Cargo.toml
=> eth api rocksdb open with secondary

src/components/finutils/Cargo.toml, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs
=> fix fn show

src/components/abciapp/Cargo.toml, src/components/abciapp/src/abci/server/callback/mod.rs, src/components/contracts/baseapp/Cargo.toml, src/components/contracts/baseapp/src/lib.rs, src/components/contracts/modules/account/Cargo.toml, src/components/contracts/modules/ethereum/Cargo.toml, src/components/contracts/modules/evm/Cargo.toml, src/components/contracts/primitives/core/Cargo.toml, src/components/contracts/primitives/storage/Cargo.toml, src/components/contracts/rpc/Cargo.toml, src/components/contracts/rpc/src/eth.rs, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs
=> Fix web3 rpc

src/components/abciapp/src/abci/staking/test.rs, src/components/finutils/src/bins/fn.rs, src/components/finutils/src/bins/stt/init/i_testing.rs, src/components/finutils/src/bins/stt/init/mod.rs, src/components/finutils/src/bins/stt/stt.rs, src/components/finutils/src/common/ddev/init.rs, src/components/finutils/src/common/evm.rs, src/components/finutils/src/common/mod.rs, src/components/finutils/src/common/utils.rs, src/components/finutils/src/lib.rs, src/components/finutils/src/transaction.rs, src/components/finutils/src/txn_builder/mod.rs, src/components/wallet_mobile/src/rust/transaction.rs, src/components/wasm/src/wasm.rs, src/ledger/src/data_model/mod.rs
=> wasm add memo

.github/workflows/Release.yml, Makefile
=> change the dockerhub to a new repo.

Makefile
=> Fix new dockerhub CI error

src/components/abciapp/src/abci/server/tx_sender.rs
=> Increase transaction size limit

src/components/config/src/abci/mod.rs
=> fix checkpoint

.github/workflows/Main.yml, Cargo.toml, src/components/abciapp/Cargo.toml, src/components/abciapp/src/abci/server/callback/mod.rs, src/components/abciapp/src/api/query_server/query_api/mod.rs, src/components/contracts/modules/account/src/lib.rs, src/components/contracts/modules/ethereum/src/impls.rs, src/components/contracts/modules/evm/src/runtime/stack.rs, src/components/contracts/primitives/rpc-core/src/types/bytes.rs, src/components/contracts/primitives/rpc-core/src/types/index.rs, src/components/contracts/primitives/rpc-server/src/lib.rs, src/components/contracts/rpc/src/eth.rs, src/components/wallet_mobile/src/rust/account.rs, src/components/wallet_mobile/src/rust/data_model.rs, src/ledger/src/data_model/mod.rs, src/ledger/src/staking/mod.rs, src/ledger/src/store/mod.rs
=> Fix export web3rpc
