src/components/finutils/src/txn_builder/mod.rs
src/components/wasm/Cargo.toml
src/components/wasm/src/wasm.rs

for Key Generation of type AXFR keypair
1. Added wasm interface for generating random anon keypairs
2. Wasm Interface for factory pattern of Anon Transfer builder

FO-465 & FO-470 Add Wasm Bindings for ABAR transfer & Wasm bindings for Key Generation of type AXFR keypair

---

src/components/contracts/modules/evm/src/impls.rs
src/components/contracts/primitives/storage/src/types/map.rs

Prior to the change, the code was being serialized before persisted to the db. Now the code is written directly to the db as raw bytes.

Fixing issue with big contract deployment

---

src/components/contracts/modules/evm/src/impls.rs
src/components/contracts/primitives/storage/src/types/map.rs

Prior to the change, the code was being serialized before persisted to the db. Now the code is written directly to the db as raw bytes.

Fixing issue with contract deployment. 

---

src/components/contracts/baseapp/src/lib.rs
src/components/contracts/modules/ethereum/Cargo.toml
src/components/contracts/modules/ethereum/src/impls.rs
src/components/contracts/modules/ethereum/tests/ethereum_db.rs

Background: Mainnet mistakingly writes TransactionIndex into chain state which shouldn't be reverted regardless of failure of transactions.
* Fetch all existing TransactionIndex data from chain state and write them into chain db when node starts up.

FO-704: Transaction index data migration from state to db

---

Makefile
src/components/finutils/src/common/mod.rs
src/components/finutils/src/txn_builder/mod.rs
tools/triple_masking/anonxfr_test_demo.sh
tools/triple_masking/bar_to_abar_convert.sh
tools/triple_masking/multi_axfr_test_demo.sh

These are the changes to integrate the fees operation with the CLI.
There is a function that computes the remainder and adds an extra output which is sent back to the sender. Even If the remainder is "0" an extra output is added. The problem to avoid having an extra output to cash back "0 FRA" is that, if the remainder is exactly the amount to pay for an extra output, once the new fees are computed the remainder becomes zero
For example for one input, and three outputs, the fees are base(0.005) + (inputs) 0.001 + (outputs) 3 * 0.002 = 0.012
So, supposing the input is 10.014 and the outputs are 5, 3, and 2 
in this case 10.014 = 5.0 + 3.0 + 2.0  + (fees) 0.012 + (remainder) 0.002
as remainder is going to be an extra output fees become fees = base(0.005) + (inputs) 0.001 + (outputs) 4 * …

Integrating anon transfer fee and remainder with txn builder and CLI

---

src/components/contracts/baseapp/src/app.rs
src/components/contracts/baseapp/src/modules.rs
src/components/contracts/modules/ethereum/src/impls.rs
src/components/contracts/modules/ethereum/src/lib.rs
src/components/contracts/primitives/core/src/module.rs

The main reason why the state root is shown as unchanged is because the “root_hash()” function returns the root hash of the last commit without including the current pending transactions.
The “store_block()” function is populating the block info with all the pending transactions and the last commit hash. This hash doesn’t include the transactions that are about to be committed.
The root hash stored for each block is delayed because the process of storing block info is called during the block ender when the current root hash hasn’t been calculated yet.
The solution to this issue would be to call “store_block” after the root hash has been calculated on the state.

FO-846: fix state root error

---

Makefile
src/components/finutils/src/bins/fn.rs
src/components/finutils/src/bins/fn.yml
src/components/finutils/src/common/mod.rs
src/components/finutils/src/txn_builder/mod.rs
src/components/wasm/src/wasm.rs
tools/triple_masking/assets_mixing_test_demo.sh
tools/triple_masking/multi_axfr_test_demo.sh

Anon assets mixing

---

src/components/finutils/src/bins/fn.rs
src/components/finutils/src/bins/fn.yml
src/components/finutils/src/common/mod.rs
src/components/finutils/src/common/utils.rs
src/components/finutils/src/txn_builder/mod.rs
src/components/wasm/src/wasm.rs
src/ledger/src/data_model/effects.rs
src/ledger/src/data_model/mod.rs
src/ledger/src/store/api_cache.rs
src/ledger/src/store/mod.rs
tools/triple_masking/abar_to_bar_convert.sh

- Changes to the ledger, CLI, wasm and integration tests to add anon fee operation for ABAR to BAR conversion

Anon Fee for ABAR to BAR

---

src/components/abciapp/Cargo.toml
src/components/contracts/modules/account/Cargo.toml
src/components/contracts/primitives/mocks/Cargo.toml
src/components/contracts/primitives/types/Cargo.toml
src/components/finutils/Cargo.toml
src/components/wasm/Cargo.toml
src/ledger/Cargo.toml
src/libs/credentials/Cargo.toml
src/libs/globutils/Cargo.toml
src/libs/sparse_merkle_tree/Cargo.toml
tools/devnet/env.sh
tools/regression/triple_masking/scripts/create_test_bars.sh
tools/regression/triple_masking/scripts/env.sh
tools/regression/triple_masking/scripts/setup_wallets.sh
tools/regression/triple_masking/test_triple_masking.sh
tools/triple_masking/bar_to_abar_convert.sh

Regression tests for triple masking

---

src/components/abciapp/Cargo.toml
src/components/finutils/src/bins/fn.rs

https://github.com/FindoraNetwork/platform/blob/16a7e7d2087b7b92db1b66b25ffe3b20f18b2110/src/components/finutils/src/bins/fn.rs#L462 https://github.com/FindoraNetwork/platform/blob/16a7e7d2087b7b92db1b66b25ffe3b20f18b2110/src/components/finutils/src/bins/fn.yml#L602

Fix: make abar2bar args same as help

---

src/ledger/src/staking/mod.rs

This method cleans up the paid delegations when the unstake reaches the block height 21 days in the future.
If an account initiates an unstake operation at block height 20, it will change its status from bond to free 21 days later at block height 113420, then it will pay the delegate at 113421 and change its status from free to paid, so the current height cannot be included in the polling here.
The following figure is the result of the test including the current height, in order to facilitate the test I will change the height of the state set to 5

fix unpaid delegation

---

src/components/abciapp/src/abci/mod.rs
src/components/abciapp/src/abci/server/callback/mod.rs
src/components/abciapp/src/bins/abcid.rs

Sleep thread to prevent begin block when exiting.
fix bug in ctrlc handler.
Fix use of IN_SAFE_ITV, thus, fix unexpected exit of platform.

Move IN_SAFE_ITV to commit section and fix bug on using of it.

---

src/components/contracts/baseapp/src/modules.rs
src/components/contracts/modules/ethereum/src/lib.rs
src/components/contracts/modules/ethereum/tests/ethereum_integration.rs
src/components/contracts/modules/evm/tests/evm_integration.rs
src/components/contracts/modules/template/tests/template_integration.rs
src/components/contracts/primitives/core/src/transaction.rs
tools/devnet/startnodes.sh
tools/regression/evm.py

1. Modified ValidateUnsigned trait - removed redundant validate call in pre execute function
2. Modified evm.py to use pending nonce when broadcasting a send transaction
3. Call apply for transaction check but only run pre-execute function
4. Updated startnodes.sh to use the variable $BIN instead of hard-coding release path

FO-968: Increment Nonce for CheckTx run mode without executing EVM transaction 

---

src/components/config/src/abci/mod.rs
src/components/contracts/modules/ethereum/src/impls.rs
src/components/contracts/modules/ethereum/src/lib.rs
src/components/contracts/modules/ethereum/tests/ethereum_db.rs

1. Added function to adjust state root field for evm blocks.
2. The migration only executes once after a flag has been set after the first execution.
3. Added unit test to assert correct functionality.

FO-863: State root data migration

---

.github/workflows/Develop.yml
.github/workflows/Features.yml
.github/workflows/Main.yml
.github/workflows/Others.yml
.github/workflows/Release.yml
container/Dockerfile-binary-image-dev
container/Dockerfile-binary-image-release

Switch the action build process to scalable action runner.
When the build triggered, AWS will receive a request in API gateway, one or several 48 vCPU, 192GB memory instance(s) will create by Lambda and register to Github for a Action runner. it will reduce the build process to around 10 mins. After the build process, the instance will automatically shut down. 

Switch action build to scalable runner

---

.gitignore
src/components/abciapp/Cargo.toml
src/components/abciapp/src/abci/server/callback/mod.rs
src/components/abciapp/src/abci/server/mod.rs
src/components/contracts/baseapp/Cargo.toml
src/components/contracts/baseapp/src/app.rs
src/components/contracts/baseapp/src/lib.rs
src/components/contracts/baseapp/src/modules.rs
src/components/contracts/modules/account/Cargo.toml
src/components/contracts/modules/account/src/lib.rs
src/components/contracts/modules/ethereum/Cargo.toml
src/components/contracts/modules/ethereum/src/impls.rs
src/components/contracts/modules/ethereum/src/lib.rs
src/components/contracts/modules/evm/Cargo.toml
src/components/contracts/modules/evm/src/impls.rs
src/components/contracts/modules/evm/src/lib.rs
src/components/contracts/modules/template/Cargo.toml
src/components/contracts/modules/template/src/lib.rs
src/components/contracts/modules/xhub/Cargo.toml
src/components/contracts/modules/xhub/src/lib.rs
src/components/contracts/primitives/core/Cargo.toml
src/components/contracts/primitives/events/Cargo.toml
src/components/contracts/primitives/mocks/Cargo.toml
src/components/contracts/primitives/storage/Cargo.toml
src/components/contracts/rpc/Cargo.toml

1.  squash some db operations in critical path
2.  replace `stateless rocksdb` with in-memory array for deliver_tx pending transactions
3.  use readlock for BaseApp CheckTx
4.  use concurrent `rust-abci`
5.  fix test and clippy failures
* **TODO**

Tps main v4

---

src/components/contracts/modules/ethereum/src/lib.rs
src/components/contracts/modules/ethereum/tests/ethereum_integration.rs
src/components/contracts/modules/evm/tests/evm_integration.rs

Fix the problem that sending that transaction to the main network will result in incorrect nonce
The main reason is because the previous pre-execution logic does not specify the height,, that is, when evm_checktx_nonce does not reach the specified height, nonce will be in the check_tx in +1, and then go to execute execute, this time will be nonce check error

fix nonce not match

---

src/components/finutils/src/common/mod.rs
src/ledger/Cargo.toml
src/ledger/src/data_model/effects.rs
src/ledger/src/data_model/mod.rs

Add a prefix to asset_type_code, FRA type does not need to be added, the main modification in the effect, in the asset_type_code to add the user_defined prefix

Add a prefix of type 'UserDefined' to asset_type_code

---

checkpoint_devnet_example.toml
src/components/abciapp/src/abci/staking/test.rs
src/components/finutils/src/bins/stt/stt.rs
src/components/finutils/src/common/evm.rs
src/components/finutils/src/common/mod.rs
src/components/finutils/src/common/utils.rs
src/components/finutils/src/txn_builder/mod.rs
src/components/wallet_mobile/src/rust/transaction.rs
src/components/wasm/src/wasm.rs

Fixes Txn building from prenotes of anonymous operations. This was happening in CLI but was not implemented for WASM and mobile wallet.

Fix wasm txn

---

src/components/contracts/primitives/types/Cargo.toml
src/components/contracts/primitives/types/src/crypto.rs

How about use address34 as the public key ?
Secp256k1: public key size is 33
Ed25519: public key size is 32
And in the zei, the XfrPublicKey is 34 (0 is the KeyType, 1..34 is the raw bytes).
And maybe we can delete `MultiSignature`, because the XfrPublicKey also supported the secp256k1 signature. Of course, this requires us to add `RecoveryId` to the signature in zei (length will 66). When calling in WASM, if it is called from metamask or like this, then add the KeyType in front of the signature.

update address32 to 34

---

src/components/finutils/src/txn_builder/mod.rs
src/components/wasm/src/wasm.rs

For the new WASM API, we allow non FRA custom Assets to have
input amounts more than the output amounts and send the extra
amount back to sender during the build process.
This requires the fee estimator to calculate any possible custom-
asset-back outputs of the anon transfer transaction and include those
in the fee calculation.
The FRA requirement calculation logic has also been made linear.

FO-1119 Fix fee for custom asset remainder

---

src/components/abciapp/Cargo.toml
src/components/config/Cargo.toml
src/components/config/src/abci/mod.rs

This reverts commit ec46b792954083c678aac674a8c0368a3875c9f2.

Revert "update btm crate version (#440)"

---

Cargo.toml

This PR bumps the Zei library to the latest version (with a fixed tag). The latest version, particularly, restore the ECC gate. 
This causes the proof size to be larger.

Bump up the Zei version in address-folding

---

Cargo.toml
src/components/contracts/baseapp/Cargo.toml
src/components/contracts/modules/account/Cargo.toml
src/components/contracts/modules/ethereum/Cargo.toml
src/components/contracts/modules/evm/Cargo.toml
src/components/contracts/primitives/core/Cargo.toml
src/components/contracts/primitives/storage/Cargo.toml
src/components/finutils/src/bins/fn.rs
src/ledger/Cargo.toml
src/ledger/src/data_model/mod.rs
src/libs/cryptohash/src/lib.rs
src/libs/sparse_merkle_tree/Cargo.toml

This PR points zei to a newer release, which will serialize the Bulletproofs over secq256k1 with some compression to reduce the proof size.

Use zei v0.2.4 in address-folding branch

---

Cargo.toml

Zei library has a renaming that may affect how data is serialized in the JSON representation. Aka, it is breaking. 
This PR bumps up to the latest version.

Bump zei from v0.2.4 to v0.2.5

---

src/components/abciapp/src/api/query_server/query_api/ledger_api.rs
src/libs/merkle_tree/src/lib.rs

Fix FO-1120
This is what is required in the documentation
eg. 09EF1DB6B67D1CBF7EBA6BD9B204611848993DF7
before: 308%
```jsonc
"validator_realtime_apy": [
8.361847871253889e+37,
2.773533508139776e+37
]
```
after: 19.2%
```jsonc
"validator_realtime_apy": [
14787890782525169040000,
76798321463198300000000
]
```

[FO-1120] fix error in calculating the value of `Latest expected Return` in api `validator_detail`

---

src/components/contracts/rpc/Cargo.toml
src/components/contracts/rpc/src/eth.rs
src/libs/merkle_tree/src/lib.rs

to indicate it.
In order to elimiate errors and warnings of blockscout, I implement returning pseudo block data before the EVM_FIRST_BLOCK_HEIGHT. Now from height 1 to EVM_FIRST_BLOCK_HEIGHT -1, request of eth_getBlockByNumber can return a block that size==0x1.
An environment var `EVM_FIRST_BLOCK_HEIGHT` is added, to avoid introducing config crate, default is 1424654.
Hash of pseudo block at EVM_FIRST_BLOCK_HEIGHT -1 is [0;32]( because parent hash of block at EVM_FIRST_BLOCK_HEIGHT is [0;32] on mainnet ).

Implement returning pseudo block before EVM_FIRST_BLOCK_HEIGHT

---

src/components/config/src/abci/mod.rs
src/ledger/src/staking/mod.rs
src/libs/merkle_tree/src/lib.rs

The problem is that when the validator received a penalty, the `delegations` in the `Delegation` structure did the deduction, while the `delegators` in the `Validator` structure did not do the deduction
Here are the results of the restoration

Fix the amount in the `delegators` that staking did not modify when it punished the `validator`

---

src/components/abciapp/src/abci/staking/mod.rs

https://github.com/FindoraNetwork/platform/pull/430
此pr修复主网会把解质押的21天内产生的奖励丢失问题
此次修复以上pr checkpoint错误导致历史数据不兼容问题
添加checkpoint之后，main分支加载主网历史数据，目前已经追上

fix undelegation missing reward bug

---

src/components/finutils/src/common/dev/init.rs
src/components/finutils/src/common/dev/mod.rs
src/ledger/src/staking/mod.rs

1.platform中设定最少validator的数量为5（VALIDATORS_MIN）,env的默认为4，导致UpdateValidator交易失败
2.自我质押的时候Delegation交易没有签名导致自我质押失败

fix fn dev

---

src/components/finutils/src/common/dev/init.rs
src/components/finutils/src/common/dev/mod.rs
src/ledger/src/staking/mod.rs

1.platform中设定最少validator的数量为5（VALIDATORS_MIN）,env的默认为4，导致UpdateValidator交易失败
2.自我质押的时候Delegation交易没有签名导致自我质押失败

fix fn dev on develop branch

---

Makefile
README.md
docs/fn_dev.md
src/components/finutils/src/bins/fn.rs
src/components/finutils/src/bins/fn.yml
src/components/finutils/src/bins/stt/init/mod.rs
src/components/finutils/src/bins/stt/stt.rs
src/components/finutils/src/common/dev/README.md
src/components/finutils/src/common/dev/init.rs
src/components/finutils/src/common/dev/mod.rs
src/ledger/src/staking/mod.rs

> https://github.com/rust-util-collections/platform/blob/main/src/components/finutils/src/common/dev/README.md
> would like to act as an upgrade page for https://wiki.findora.org/docs/developers/development_network.
>
> SEE ALSO: https://github.com/FindoraNetwork/findora-wiki/pull/224
A powerful and convenient development tool for managing local clusters of FindoraNetwork.
Its goal is to replace some existing rudimentary development environment management tools, such as: `make debug_env` and `make devnet`.
Through a `fn dev -h` we can see:
```shell
fn-dev
Manage development clusters on your localhost
USAGE:
fn dev [OPTIONS] [SUBCOMMAND]
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
-e, --env-name <ENV NAME>    The name of the target …
```

add docs for `fn dev`, and extend functions

---

src/components/contracts/primitives/mocks/Cargo.toml
src/components/contracts/primitives/types/Cargo.toml
src/components/contracts/primitives/utils/Cargo.toml
src/components/contracts/rpc/Cargo.toml

Checked: https://github.com/paritytech/libsecp256k1/blob/master/CHANGELOG.md
And reviewed 0.5 ~ 0.7.1 commits, This is a safe upgrade

Upgrade libsecp256k1 version

---

src/components/finutils/src/bins/fn.rs
src/components/finutils/src/bins/fn.yml
src/components/finutils/src/common/dev/README.md
src/components/finutils/src/common/dev/mod.rs

- add new subcmds: `fn dev start-all` and `fn dev stop-all`
- add a new flag `--force` for `fn dev create`
- add a new option `--tendermint-extra-flags` for `fn dev create`
- rename `fn dev add-node` to `fn dev push-node`
- rename `fn dev del-node` to `fn dev pop-node`
- rename `fn dev info` to `fn dev show`
- rename `fn dev info-all` to `fn dev show-all`
- rename short names of `fn dev create -E/T/A` to `fn dev create -x/D/d`
- optimize docs

tuning some details of `fn dev`

---

src/ledger/src/data_model/mod.rs

The command line `fn` is now signed with the transaction body, but `check_tx` does not perform the prism transaction check, so this pr fixes the problem.

Fix `check_tx` bug that not check prism tx

---

src/components/finutils/src/common/evm.rs
src/components/finutils/src/common/mod.rs
src/components/finutils/src/common/utils.rs
src/components/finutils/src/txn_builder/mod.rs
src/components/wasm/src/wasm.rs
src/ledger/src/data_model/mod.rs
src/ledger/src/store/utils.rs

New field `pubkey_sign_map` in the `Transaction` struct, and `check_tx` method is compatible with the previous data format

Add new field `pubkey_sign_map` for `Transaction` struct

---

src/components/contracts/baseapp/Cargo.toml
src/components/contracts/modules/account/Cargo.toml
src/components/contracts/modules/ethereum/Cargo.toml
src/components/contracts/modules/evm/Cargo.toml
src/components/contracts/modules/evm/precompile/Cargo.toml
src/components/contracts/primitives/core/Cargo.toml
src/components/contracts/primitives/storage/Cargo.toml

1. update storage version to v1.0.0 to make commit faster on history(auxiliary) data. 

update storage to speedup catch-up

---

src/components/abciapp/src/api/query_server/query_api/ledger_api.rs
src/components/abciapp/src/api/query_server/query_api/server.rs
src/ledger/src/store/mod.rs

Fixes App hash mismatch caused by a bug in get_state_commitment

fix get_state_commitment for ledger_api and block commit

---

src/components/wasm/Cargo.toml

- [] make fmt
- [] make lint
latest wasm-bindgen is incompatible, because of BigInt, now rollback to 0.2.73

Rollback wasm bindgen

---

.github/dependabot.yml

This seems to make more sense to ask dependabot to work on develop rather than main, unless it is a crucial security update.

Change the target branch of dependabot

---

.github/dependabot.yml
Cargo.toml
src/components/abciapp/Cargo.toml
src/components/contracts/modules/account/Cargo.toml
src/components/contracts/primitives/mocks/Cargo.toml
src/components/contracts/primitives/types/Cargo.toml
src/components/finutils/Cargo.toml
src/components/wasm/Cargo.toml
src/ledger/Cargo.toml
src/libs/credentials/Cargo.toml
src/libs/globutils/Cargo.toml

It appears that dependabot has caused the main branch to have some incompatibility issues not shown up before. 
The `stable-main` restores the main branch. Before merging, we need to force push the main before the last chunk of the dependabot update.

Tracking issue for restoring the main branch

---

.github/workflows/Develop.yml
.github/workflows/DevelopArm.yml
.github/workflows/Features.yml
.github/workflows/Fn.yml
.github/workflows/Main.yml
.github/workflows/Others.yml
.github/workflows/Release.yml
.github/workflows/ReleaseArm.yml
.github/workflows/WasmCat.yml
.github/workflows/WasmCatDelete.yml

This PR performs some upgrades to the actions modules. This is necessary since GitHub Actions appear to want to disable some deprecated features.

Upgrade actions/checkout and actions/cache in GitHub CI

---

Cargo.toml
src/components/abciapp/Cargo.toml
src/components/contracts/modules/account/Cargo.toml
src/components/contracts/modules/evm/Cargo.toml
src/components/contracts/primitives/mocks/Cargo.toml
src/components/contracts/primitives/types/Cargo.toml
src/components/finutils/Cargo.toml
src/components/wallet_mobile/Cargo.toml
src/components/wasm/Cargo.toml
src/ledger/Cargo.toml
src/libs/credentials/Cargo.toml
src/libs/globutils/Cargo.toml
src/libs/sparse_merkle_tree/Cargo.toml

Previously the platform is pointing to the latest version of Noah. This should no longer work as we are changing the dependency at this moment. This PR fixes so.

Use a tagged version of Noah

---

Cargo.toml
src/components/abciapp/Cargo.toml
src/components/abciapp/src/abci/server/callback/mod.rs
src/components/abciapp/src/api/query_server/query_api/ledger_api.rs
src/components/abciapp/src/api/query_server/query_api/mod.rs
src/components/contracts/baseapp/src/tm_events.rs
src/components/contracts/modules/account/Cargo.toml
src/components/contracts/modules/ethereum/src/impls.rs
src/components/contracts/modules/evm/Cargo.toml
src/components/contracts/modules/evm/src/system_contracts.rs
src/components/contracts/modules/evm/src/utils.rs
src/components/contracts/modules/evm/test-vector-support/src/lib.rs
src/components/contracts/modules/evm/tests/utils/solidity.rs
src/components/contracts/primitives/mocks/Cargo.toml
src/components/contracts/primitives/types/Cargo.toml
src/components/contracts/primitives/types/src/crypto.rs
src/components/contracts/primitives/utils/src/ecdsa.rs
src/components/contracts/primitives/wasm/src/wasm.rs
src/components/contracts/rpc/src/eth.rs
src/components/finutils/Cargo.toml
src/components/wallet_mobile/Cargo.toml
src/components/wasm/Cargo.toml
src/ledger/Cargo.toml
src/ledger/src/store/mod.rs
src/libs/bitmap/src/test.rs
src/libs/credentials/Cargo.toml
src/libs/globutils/Cargo.toml
src/libs/globutils/src/wallet.rs
src/libs/sparse_merkle_tree/Cargo.toml
src/libs/sparse_merkle_tree/src/lib.rs

The previous version of noah didn't use a tagged version of ark-bulletproofs-secq256k1, however, we plan to make changes to it. 
This PR fixes so for the develop branch. 

Use noah v0.3.0 to make sure all crypto dependencies are tagged

---

src/components/contracts/primitives/wasm/Cargo.toml
src/components/finutils/Cargo.toml
src/components/wallet_mobile/Cargo.toml
src/components/wasm/Cargo.toml
src/libs/credentials/Cargo.toml

https://pullanswer.com/questions/import-__wbindgen_bigint_from_i64-with-non-js-compatible-func-sigurature-i64-as-parameter
The latest version of wasm_bindgen has a bug so we roll back.

Rollback wasm_bindgen version to 0.2.73

---

container/Dockerfile-binary-image-dev

A concern about the nightly test waiting time is that probably the nodes are too slow. This is possible because the nightly image uses a version of the platform library without Rust optimization.

Use Rust optimization when compiling the instance for Nightly test

---

container/Dockerfile-binary-image-dev

Reverts FindoraNetwork/platform#767
This causes an unpleasant effect on the checkpoint.toml that fails the transaction. In addition, it seems that the image is also compiled with `--release`, so this PR is unnecessary as well.

Revert "Use Rust optimization when compiling the instance for Nightly test"

---

src/components/config/src/abci/mod.rs

The new field must delete the old checkpoint so that Findorad can generate it automatically to take effect. If you need to change this method, you need to re-code and load the rules for checkpoints. 
Currently, this PR only fixes the issue of incorrect `fns_registry` values ​​under `debug_env` and `!debug_env`.

Fix the issue where the value of fns_registry is incorrect under !debug_env.

---

src/components/contracts/modules/account/src/impls.rs

Fixing the error in abci due to inconsistent line numbers causing data and reson's data to be inconsistent with the entire network when reaching tendermint, resulting in an inconsistency in block.header.LastResultsHash.
before
```jsonc
{"Call":{"exit_reason":{"Error":{"Other":"SimpleError { msg: SimpleMsg { err: \"insufficient balance\", file: \"src/components/contracts/modules/account/src/impls.rs\", line: 65, column: 16 }, cause: None }"}},"value":[],"used_gas":"0xb8b1","logs":[]}}
```
after
```jsonc
{"Call":{"exit_reason":{"Error":{"Other":"SimpleError { msg: SimpleMsg { err: \"insufficient balance\", file: \"src/components/contracts/modules/account/src/impls.rs\", line: 66, column: 16 }, cause: None }"}},"value":[],"used_gas":"0xb8b1","logs":[]}}
```

fix td block.header.lastResultsHash bug

---

src/components/contracts/modules/evm/precompile/anemoi/Cargo.toml
src/components/contracts/modules/evm/precompile/anemoi/src/lib.rs

Previously, the Anemoi precompile uses the Noah library directly. For unified version control, in this PR, we change to use platform-lib-noah only.

Let the Anemoi precompile use the platform-lib-noah library

---

src/components/abciapp/src/abci/server/callback/mod.rs
src/components/contracts/baseapp/src/app.rs
src/components/contracts/baseapp/src/modules.rs
src/components/contracts/baseapp/src/staking.rs
src/components/contracts/modules/ethereum/src/lib.rs
src/components/contracts/modules/ethereum/tests/ethereum_integration.rs
src/components/contracts/modules/evm/contracts/EVMStaking.abi.json
src/components/contracts/modules/evm/precompile/src/lib.rs
src/components/contracts/modules/evm/src/lib.rs
src/components/contracts/modules/evm/src/utils.rs
src/components/contracts/modules/template/tests/template_integration.rs
src/components/contracts/primitives/core/src/module.rs
src/ledger/src/staking/evm.rs
src/ledger/src/staking/mod.rs

add importCoinBase

---

src/components/abciapp/src/api/query_server/query_api/ledger_api.rs
src/ledger/src/store/mod.rs

fix rpc query_utxos

---

src/components/abciapp/src/abci/server/callback/mod.rs
src/components/contracts/modules/account/src/impls.rs
src/components/contracts/modules/evm/precompile/frc20/src/lib.rs
src/components/contracts/primitives/enterprise-web3/Cargo.toml
src/components/contracts/primitives/enterprise-web3/src/lib.rs
src/components/contracts/primitives/traits/src/account.rs

import allowances to redis

---

src/components/abciapp/src/abci/server/callback/mod.rs
src/components/abciapp/src/abci/staking/mod.rs
src/components/config/src/abci/mod.rs
src/components/contracts/baseapp/src/app.rs
src/components/contracts/baseapp/src/modules.rs
src/components/contracts/baseapp/src/staking.rs
src/components/contracts/modules/ethereum/src/lib.rs
src/components/contracts/modules/evm/contracts/EVMStaking.abi.json
src/components/contracts/modules/evm/src/lib.rs
src/components/contracts/modules/evm/src/runtime/runner.rs
src/components/contracts/modules/evm/src/utils.rs
src/components/contracts/primitives/core/src/module.rs
src/components/finutils/src/common/mod.rs
src/components/finutils/src/txn_builder/mod.rs
src/ledger/src/staking/evm.rs
src/ledger/src/staking/ops/replace_staker.rs

add coninbase mint 、remove importCoinBase、remove coinbasemintevent、fix decimal

---

src/components/abciapp/src/abci/server/callback/mod.rs
src/components/abciapp/src/abci/staking/mod.rs
src/components/finutils/src/bins/fn.yml
src/ledger/src/data_model/effects.rs
src/ledger/src/staking/mod.rs
src/ledger/src/store/mod.rs

The DefineAsset Operation has the raw asset code whereas IssueAsset Operation has the derived asset code.
Currently if both the operations are sent in the same txn for a new asset it fails because the Asset code don't match. This is fixed by comparing the derived asset code from newly defined assets in the txn.

Fix failure for DefineAsset and IssueAsset operation sent in same txn

---

Cargo.toml
src/components/contracts/modules/evm/precompile/Cargo.toml
src/components/contracts/modules/evm/precompile/ed25519_verify/Cargo.toml
src/components/contracts/modules/evm/precompile/ed25519_verify/src/lib.rs
src/components/contracts/modules/evm/precompile/src/lib.rs
src/components/finutils/src/bins/fn.rs
src/components/finutils/src/bins/fn.yml

add precompile ed25519 verify

---

src/components/contracts/rpc/src/eth.rs

fix  hash mismatch

---

src/components/abciapp/src/abci/server/callback/mod.rs
src/components/config/src/abci/mod.rs
src/components/contracts/baseapp/src/app.rs
src/components/contracts/primitives/types/src/crypto.rs
src/components/finutils/src/bins/fn.rs
src/components/finutils/src/txn_builder/mod.rs
src/ledger/src/staking/mod.rs
src/ledger/src/staking/ops/claim.rs

filter input
